name: Keep Render Server Awake

on:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes

jobs:
  wake_server:
    runs-on: ubuntu-latest

    steps:
      - name: Send HTTP Request to Keep Server Awake
        run: curl -s -o /dev/null https://cryphorizon-server.onrender.com

